### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by collegeimprovements** [benwalks/photogram#10]
Hey Ben,

I find your series hilarious. It's one of the few tutorial which I could follow because it was lucid and very informative.

Thanks a lot for this. Hope to see more from you in the future.

**Comment by benwalks** [comment]
Haha, thanks man!  I love that you've sent me a lovely message via a GitHub issue too!

Stay tuned, there's plenty more to come.  I've been interviewing a few dev shops at the moment, trying to work out what they want from self-taught developers (which will turn into blog posts) and I'm almost ready to start the next Let's Build series!

Thanks again!
