### ISSUE TITLE
Upgraded verson of the photogram is available.

### ISSUE THREAD

**Issue by shirshak55** [benwalks/photogram#15]
We have really worked hard on your tutorial and made a better version of it. Soon we will be adding more feature. Thanks benwalks for your awesome tutorial.

https://github.com/bloggervista/Bee-Connect

If anyone wants to contribute feel free to PR .

**Comment by benwalks** [comment]
Congrats on what you've achieved @bloggervista, it really looks great!

**Comment by shirshak55** [comment]
Thanks. There were some problems regarding ajax and other which we have fixed it. And rails has been upgraded. SO anyone can check code if they found problem with tutorial :) Thanks again.
