### ISSUE TITLE
It is computationally costly if there are over a thousand comments to load 

### ISSUE THREAD

**Issue by Heizenburg** [benwalks/photogram#16]
Great tutorial, however, I have been wondering if a load more button would be efficient and less harsh to the database than to load all the remaining comments provided that the number is in the thousands if not millions (hypothetically).

**Comment by benwalks** [comment]
Absolutely @Heizenburg, that would be the best way to do it. The tutorial didn't handle a number of use cases like this, but check out some of the pagination gems or roll out a pagination features for comments yourself using database offsets!
